# Generated by Django 5.2.7 on 2025-10-21 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='quest_covers/')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10)),
                ('estimated_time', models.IntegerField(default=30, help_text='Время прохождения в минутах')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('play_count', models.IntegerField(default=0, verbose_name='Количество прохождений')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, related_name='quests', to='quests.tag')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_icons/')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quests.quest')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сцены')),
                ('content', models.TextField(verbose_name='Текст сцены')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('is_starting_scene', models.BooleanField(default=False, verbose_name='Начальная сцена')),
                ('is_ending_scene', models.BooleanField(default=False, verbose_name='Финальная сцена')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='scene_backgrounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='quests.quest')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст выбора')),
                ('order', models.IntegerField(default=0)),
                ('next_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_choices', to='quests.scene', verbose_name='Следующая сцена')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quests.scene')),
            ],
            options={
                'verbose_name': 'Выбор',
                'verbose_name_plural': 'Выборы',
                'ordering': ['order'],
            },
        ),
    ]
